# Generated by Django 4.2.1 on 2023-05-15 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='imgs',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.CharField(max_length=5000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=500, verbose_name='Короткое описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgs', models.ImageField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1, upload_to='django_media/', verbose_name='Изображение')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Локация')),
            ],
        ),
    ]
