# Generated by Django 4.2.1 on 2023-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_image_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number_image',
            field=models.CharField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1, max_length=6, verbose_name='Номер фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imgs',
            field=models.ImageField(upload_to='django_media/', verbose_name='Изображение'),
        ),
    ]
