# Generated by Django 4.2.1 on 2023-05-15 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_image_number_image_alter_image_imgs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1, max_length=6, verbose_name='Номер фотографии'),
        ),
    ]
