# Generated by Django 4.2.1 on 2023-05-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_image_places'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['number_image'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(choices=[(1, 'Первая'), (2, 'Вторая')], default=1, verbose_name='Номер фотографии'),
        ),
    ]
