# Generated by Django 4.2.1 on 2023-05-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_image_options_alter_image_number_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(blank=True, choices=[(1, 'Первая'), (2, 'Вторая')], db_index=True, default=1, null=True, verbose_name='Номер фотографии'),
        ),
    ]
