# Generated by Django 4.2.1 on 2023-06-09 07:19

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_alter_place_description_long_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imgs',
            new_name='img',
        ),
        migrations.AlterField(
            model_name='image',
            name='number_image',
            field=models.IntegerField(blank=True, db_index=True, default=1, verbose_name='Номер фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='places',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое Описание'),
        ),
    ]
