# Generated by Django 4.2.1 on 2023-06-13 05:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_rename_imgs_image_img_alter_image_number_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='places',
            new_name='place',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True, verbose_name='Краткое Описание'),
        ),
    ]
