version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: pablo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wheretogo
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pablo -d wheretogo"]
      interval: 5s
      timeout: 30s
      retries: 5
    container_name: where_to_go

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: