version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: psql://test:password@db:5432/test
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    container_name: where_to_go_app
    volumes:
      - ./Where_to_go/:/where_to_go/Where_to_go
  db:
    image: postgres:12.4-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    restart: always
    ports:
    - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 30s
      retries: 5
    container_name: where_to_go

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: